name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:         # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Generate the snake animation
      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: DemmyJay-99
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # 3️⃣ Push the generated files to the output branch
      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
